# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b51a3268ede12495bb7f7dd5641b14a0cf649f4a22f34023bb268692812cc46081caf91c4e6a550787afd64453ec6c11d5e9b107d4c96e86bdf95b8427e87ae0

test:
  secret_key_base: 805e0bdf2097cdedafc9bd2d0ed7a22b8c52e85f4ebed35ea3dd8ab6db50446b1032c0e5373a0f0c393d3cce696673219f9a0bf4809d8c554d60172cfe018815

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
